name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup signing
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks
          cat > android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=app/upload-keystore.jks
          EOF
          test -s android/app/upload-keystore.jks
          test -s android/key.properties
          echo "Signing files created successfully"

      - name: Get dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build Release AAB
        run: flutter build appbundle --release


      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: MediaMint-release-AAB
          path: build/app/outputs/bundle/release/app-release.aab
